language: python
before_script:
  - pip install -U vl
  - vl --version
script:
  - vl README.md -t 5 --debug -w gamesounds.xyz,vungle.com,renderhjs.net,famitracker.com,visualstudio.com -a 503,405,401
